-- Development seed data — do NOT run in production
-- Populates enough records to exercise the API locally.

INSERT INTO merchants (id, name, email, business_type, status, stripe_account_id)
VALUES
    ('11111111-0000-0000-0000-000000000001', 'Acme Widgets Inc.', 'dev@acmewidgets.com', 'company', 'active', 'acct_dev_001'),
    ('11111111-0000-0000-0000-000000000002', 'Testco LLC', 'dev@testco.io', 'individual', 'active', NULL);

-- API key hashes are HMAC-SHA256 of 'ak_test_devkey1234' with salt 'dev_salt'
-- Real keys are generated by src/utils/crypto.js#generateApiKey
INSERT INTO api_keys (merchant_id, key_hash, name, scopes)
VALUES
    ('11111111-0000-0000-0000-000000000001', 'deadbeef_placeholder_hash_1', 'Default key', ARRAY['payments:read','payments:write','customers:read','customers:write','transactions:read']),
    ('11111111-0000-0000-0000-000000000002', 'deadbeef_placeholder_hash_2', 'Read-only key', ARRAY['payments:read','customers:read','transactions:read']);

INSERT INTO customers (id, merchant_id, email, first_name, last_name, phone, country, kyc_status)
VALUES
    ('22222222-0000-0000-0000-000000000001', '11111111-0000-0000-0000-000000000001', 'jane@example.com', 'Jane', 'Smith', '+12025550142', 'US', 'approved'),
    ('22222222-0000-0000-0000-000000000002', '11111111-0000-0000-0000-000000000001', 'bob@example.com',  'Bob',  'Jones', '+14155550199', 'US', 'pending'),
    ('22222222-0000-0000-0000-000000000003', '11111111-0000-0000-0000-000000000002', 'ali@example.com',  'Ali',  'Hassan','+971501234567','AE', 'not_started');
